server:
  port: 9088
spring:
  application:
    name: system
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 200633
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册


